name: difference_calc
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
          pip install poetry
          poetry install
    - name: Run linter and pytest
      run: |
        make lint
    
